version: '3.7'

services:
  db:
   image: mysql:5.7
   platform: linux/amd64
   volumes:
     - db_data:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: wnw
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress

  wordpress:
   depends_on:
     - db
   image: wordpress:latest
   ports:
     - "3000:80"
   volumes:
      - ./wp-content:/var/www/html/wp-content/
      - ./config/wp-config.php:/var/www/html/wp-config.php
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "3081:80"
    environment:
      UPLOAD_LIMIT: 300M


volumes:
    db_data: {}
